# Generated by Django 3.0.8 on 2020-07-25 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='about_myself',
            field=models.TextField(blank=True, null=True),
        ),
    ]
