# Generated by Django 3.0.8 on 2020-07-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileApp', '0005_auto_20200727_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='date_registration',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]

