# Generated by Django 3.0.8 on 2020-07-29 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileApp', '0007_profilemodel_is_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='is_online',
        ),
    ]
