# Generated by Django 3.0.8 on 2020-07-29 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileApp', '0008_auto_20200729_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='facebook_link',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='instagram_link',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='telegram_link',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='vk_link',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='whatsapp_link',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
