# Generated by Django 3.0.8 on 2020-07-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0004_auto_20200715_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='image',
            field=models.ImageField(default='images/test-photo.jpg', upload_to='images/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
