# Generated by Django 3.0.8 on 2020-07-21 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0006_auto_20200721_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagmodel',
            name='count_of_uses',
            field=models.IntegerField(default=0),
        ),
    ]
