# Generated by Django 3.0.8 on 2020-07-21 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0007_tagmodel_count_of_uses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tagmodel',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='tags',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Articles.TagModel'),
        ),
    ]
