# Generated by Django 3.0.8 on 2020-07-21 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0008_auto_20200721_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlemodel',
            name='tags',
        ),
    ]
