# Generated by Django 3.1 on 2020-08-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0012_commentanswermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='text',
            field=models.TextField(default='', max_length=50000, verbose_name='Text'),
        ),
    ]
