# Generated by Django 3.0.8 on 2020-07-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0005_auto_20200718_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='tags',
            field=models.CharField(default='', max_length=5000, verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='image',
            field=models.ImageField(blank=True, default='images/test-photo.jpg', null=True, upload_to='images/', verbose_name='Изображение'),
        ),

    ]
