# Generated by Django 3.0.8 on 2020-07-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileApp', '0002_profilemodel_about_myself'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='face_image',
            field=models.ImageField(blank=True, default='icons/FACE_ICON.png', null=True, upload_to='icons/', verbose_name='Icon'),
        ),
    ]
