# Generated by Django 3.0.8 on 2020-07-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileApp', '0004_auto_20200726_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='birth_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
